# Use a base image for the final runtime
FROM ghcr.io/graalvm/graalvm-ce:ol9-java17-22.3.2

# Set the working directory
WORKDIR /app

# Copy the native image binary from the builder stage
COPY target/demo-0.0.1-SNAPSHOT.jar /app

# Set the entry point for the container
CMD ["java", "-jar", "demo-0.0.1-SNAPSHOT.jar"]
